/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Inderdeep
 */
public class PLAY extends javax.swing.JFrame {

    /**
     * Creates new form PLAY
     */
    public PLAY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        num = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        o12 = new javax.swing.JLabel();
        o13 = new javax.swing.JLabel();
        o16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        o6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        o9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        o11 = new javax.swing.JLabel();
        o18 = new javax.swing.JLabel();
        blast = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        o17 = new javax.swing.JLabel();
        PRIZE = new javax.swing.JLabel();
        lost = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        win1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        op4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        op3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        o5 = new javax.swing.JLabel();
        op1 = new javax.swing.JLabel();
        op2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        win = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num.setFont(new java.awt.Font("Agency FB", 1, 60)); // NOI18N
        jPanel1.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 80, 70));

        display.setBackground(new java.awt.Color(51, 51, 51));
        display.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        display.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/role.jpg"))); // NOI18N
        display.setOpaque(true);
        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 220, 140));

        clock.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        clock.setForeground(new java.awt.Color(204, 0, 0));
        clock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/count.gif"))); // NOI18N
        jPanel1.add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 220, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 10, 170));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 740, 10));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        o12.setBackground(new java.awt.Color(0, 0, 0));
        o12.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        o12.setText("/");
        o12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o12MouseClicked(evt);
            }
        });

        o13.setBackground(new java.awt.Color(0, 0, 0));
        o13.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        o13.setForeground(new java.awt.Color(204, 0, 0));
        o13.setText("4");
        o13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o13MouseClicked(evt);
            }
        });

        o16.setBackground(new java.awt.Color(0, 0, 0));
        o16.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        o16.setForeground(new java.awt.Color(102, 102, 0));
        o16.setText("1");
        o16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(o12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(o16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o12, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(o13, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(o16, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 300, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        o6.setBackground(new java.awt.Color(0, 0, 0));
        o6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        o6.setText("! WINNING PRIZE MONEY !");
        o6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o6MouseClicked(evt);
            }
        });
        jPanel2.add(o6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 240, 38));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 450, 10));

        o9.setBackground(new java.awt.Color(0, 0, 0));
        o9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        o9.setForeground(new java.awt.Color(204, 204, 0));
        o9.setText("0000");
        o9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o9MouseClicked(evt);
            }
        });
        jPanel2.add(o9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 240, 38));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 260, 10));

        o11.setBackground(new java.awt.Color(0, 0, 0));
        o11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        o11.setText("! WINNING MONEY !");
        o11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o11MouseClicked(evt);
            }
        });
        jPanel2.add(o11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 200, 70));

        o18.setBackground(new java.awt.Color(0, 0, 0));
        o18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        o18.setForeground(new java.awt.Color(102, 102, 0));
        o18.setText("0000");
        o18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o18MouseClicked(evt);
            }
        });
        jPanel2.add(o18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 260, 140));

        blast.setBackground(new java.awt.Color(51, 51, 51));
        blast.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        blast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/blast.gif"))); // NOI18N
        jPanel1.add(blast, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -20, 190, 281));
        blast.setVisible(false);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 10, 370));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 990, 10));

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        o17.setBackground(new java.awt.Color(0, 0, 0));
        o17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        o17.setText("QUESTION FOR :");
        o17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o17MouseClicked(evt);
            }
        });
        jPanel6.add(o17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        PRIZE.setBackground(new java.awt.Color(0, 0, 0));
        PRIZE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PRIZE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRIZEMouseClicked(evt);
            }
        });
        jPanel6.add(PRIZE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 370, 50));

        lost.setBackground(new java.awt.Color(204, 0, 51));
        lost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/lost.gif"))); // NOI18N
        lost.setText("NAME");
        lost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lostMouseClicked(evt);
            }
        });
        jPanel1.add(lost, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, 160));
        lost.setVisible(false);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 740, 10));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 10, 360));

        win1.setBackground(new java.awt.Color(204, 0, 51));
        win1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        win1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/modi.gif"))); // NOI18N
        win1.setText("NAME");
        win1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                win1MouseClicked(evt);
            }
        });
        jPanel1.add(win1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 160, 240));
        win1.setVisible(false);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 10, 170));

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setLayout(null);

        op4.setBackground(new java.awt.Color(0, 0, 0));
        op4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op4.setText("NAME");
        op4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op4MouseClicked(evt);
            }
        });
        jPanel4.add(op4);
        op4.setBounds(360, 250, 360, 110);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel5.setOpaque(true);
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, 240, 740, 10);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3);
        jLabel3.setBounds(350, 130, 10, 230);

        op3.setBackground(new java.awt.Color(0, 0, 0));
        op3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op3.setText("NAME");
        op3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op3MouseClicked(evt);
            }
        });
        jPanel4.add(op3);
        op3.setBounds(0, 250, 350, 110);

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        o5.setBackground(new java.awt.Color(255, 51, 51));
        o5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        o5.setText("NAME");
        o5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o5MouseClicked(evt);
            }
        });
        jPanel5.add(o5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 610, 70));

        jPanel4.add(jPanel5);
        jPanel5.setBounds(50, 30, 620, 80);

        op1.setBackground(new java.awt.Color(0, 0, 0));
        op1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op1.setText("NAME");
        op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op1MouseClicked(evt);
            }
        });
        jPanel4.add(op1);
        op1.setBounds(0, 140, 350, 100);

        op2.setBackground(new java.awt.Color(0, 0, 0));
        op2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        op2.setText("NAME");
        op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op2MouseClicked(evt);
            }
        });
        jPanel4.add(op2);
        op2.setBounds(360, 140, 360, 100);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel9.setOpaque(true);
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 130, 740, 10);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 720, 360));

        win.setBackground(new java.awt.Color(204, 0, 51));
        win.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        win.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/k.gif"))); // NOI18N
        win.setText("NAME");
        win.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winMouseClicked(evt);
            }
        });
        jPanel1.add(win, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 180, 250, 240));
        win.setVisible(false);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void display(String question ,String option1 ,String  option2,String  option3,String  option4)
    {
        o5.setText(" "+question);
        op1.setText(" a). "+option1);
        op2.setText(" b). "+option2);
        op3.setText(" c). "+option3);
        op4.setText(" d). "+option4);
        PRIZE.setText(" Rs. "+money);
  
    }
    
    //making list
            ArrayList<String> question=new ArrayList<String>();
            ArrayList<String> answer=new ArrayList<String>();
            ArrayList<String> option1=new ArrayList<String>();
            ArrayList<String> option2=new ArrayList<String>();
            ArrayList<String> option3=new ArrayList<String>();
            ArrayList<String> option4=new ArrayList<String>();
            ArrayList<String> prize=new ArrayList<String>();
            
            // number of elements in QUESTION BANK
            int counter=0;
            
            //answer and money
             String ans,money;
                
    void game_engine()
    {
         try
        {
            //DOING CONNECTION

            String qry="Select * from question_bank ",s1,s2,s3,s4,s5;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root",""); 
            Statement smt= con.createStatement();
            ResultSet rs=smt.executeQuery(qry);
         
            
            while(rs.next())
            {
               counter++; 
               question.add(rs.getString("question"));
               option1.add(rs.getString("option1"));
               option2.add(rs.getString("option2"));
               option3.add(rs.getString("option3"));
               option4.add(rs.getString("option4"));
               answer.add(rs.getString("answer"));
               prize.add(rs.getString("prize"));
            }
            
            // starting
            start_game();
    
   
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Oooopppss !! \n Name Already Exist");
            e.printStackTrace();
        }  
      
    }
    
    
    //////////////// TIMER THREAD
    int j=10;
    
           Thread th = new Thread()
           {          
                      public void run()
                       {
                         for(int i=50;i>=0;i--)
                          { 
                             if(j>6)
                              {
                                  num.setText("  "+j);
                              }
                          
                             else if(j==0)
                             {
                               clock.hide();
                               blast.setVisible(true);
                               wrong();
                             }  
                             else
                             {
                               num.hide();
                               display.hide();
                             }  
                             
                             j--;
          
                               //thread
                               try
                                {
                                 Thread.sleep(1000);
                                }
                               catch(Exception e)
                                {
                                  e.printStackTrace();
                                }
                 
        }
        
       }
     };
           
    // show correct 
        
 
   /////////////////////////// PLAY FUNCTION
           
          void play()
              
            {   
               
                System.out.println("In Thread");
                 
              String s1 = null,s2 = null,s3 = null,s4 = null,s5 = null;   
                 
              Iterator itr1=question.iterator();    
              Iterator itr2=option1.iterator();
              Iterator itr3=option2.iterator();
              Iterator itr4=option3.iterator();
              Iterator itr5=option4.iterator();
              Iterator itr6=answer.iterator();
              Iterator itr7=prize.iterator();
                
       
              
                 
                 //Setting question and answer
                 //itrating to question number
                 
                 for(int i=0;i<question_number;i++)
                 {   
                  //setting money
                   money = (String) itr7.next();
                 //setting answer 
                  ans= (String) itr6.next();
                  
                  s1=(String) itr1.next();
                  s2=(String) itr2.next();
                  s3=(String) itr3.next();
                  s4=(String) itr4.next();
                  s5=(String) itr5.next();
                 }
                 //display question
                display(s1,s2,s3,s4,s5);
                 //starting timer
                  th.resume();
      
             
            }
           
          
      void sound()
      {
           try{
            InputStream music;
music=new FileInputStream(new File("C:\\Users\\Inderdeep\\Desktop\\WEB\\applause-8.wav"));
AudioStream audios=new AudioStream(music);
AudioPlayer.player.start(audios);
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}

      }
 
  // START FUNCTION  
    void start_game()
    {
           //starting play
           play();
         
    }
    
   // QUESTION NUMBER
     int question_number=1;
     
 
     
      // TIMER FOR SECOND
     Thread tm = new Thread()
     {
         public void run()
         {
             op4.setVisible(true);
             
             for(int i=0;i<25;i++)
             {
                        
        //stoping clock
         th.suspend();
                 
         
         // showing win panel
         win.setVisible(true);
         win1.setVisible(true);
         
   
                 try {
                     Thread.sleep(1800);
                 } catch (InterruptedException ex) {
                     Logger.getLogger(PLAY.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
                if(i%5==0)
                {
                    correct();
                    pend();
                }
             }
             
         }
     };
      
   
     
     
     // susspending the thread
      
     void pend()
     {
         tm.suspend();
     }
     
     
   // CORRECT questioin
   void correct()
    {

         clock.setVisible(false);
         blast.setVisible(false);
        // INCREMENT QUESTION
        question_number++;
        
        // SET WINNING MONEY
        o18.setText("Rs."+money);
        
        //going to next question
        
        if(question_number<=counter)
        {
            o16.setText(""+question_number);
            reset();
            start_game();
        }
        else 
        {
            
             try{
            InputStream music;
music=new FileInputStream(new File("C:\\Users\\Inderdeep\\Desktop\\WEB\\slot-machine-daniel_simon.wav"));
AudioStream audios=new AudioStream(music);
AudioPlayer.player.start(audios);
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}
            
            o5.setText("         !!!!!  YOU WIN !!!!");
            o5.setOpaque(true);
            o5.setBackground(Color.green);
        }
        
        
    }
   
   void wrong()
   {
       try{
            InputStream music;
music=new FileInputStream(new File("C:\\Users\\Inderdeep\\Desktop\\WEB\\cartoon010.wav"));
AudioStream audios=new AudioStream(music);
AudioPlayer.player.start(audios);
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}
       
       
       o5.setOpaque(true);
       lost.setVisible(true);
       o5.setText("                               !   YOU LOST    !  ");
       th.suspend();
       display.hide();
       clock.setVisible(false);
       num.setVisible(false);
       blast.show();
       
   }
    
   void reset()
   {
       // restting time
       j=10;
       
       // re-setting all options
       
          op1.setText("");
          op1.setOpaque(false);
          
          op2.setText("");
          op2.setOpaque(false);
          
          op3.setText("");
          op3.setOpaque(false);
          
          op4.setText("");
          op4.setOpaque(false);
          
       // resetting clock
       
           blast.hide();
           num.setVisible(true);
           clock.setVisible(true);
           
       //win
        win.setVisible(false);
        win1.setVisible(false);
               
   }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
       try{
            InputStream music;
music=new FileInputStream(new File("C:\\Users\\Inderdeep\\Desktop\\WEB\\strings3.wav"));
AudioStream audios=new AudioStream(music);
AudioPlayer.player.start(audios);
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
}

      //taling value from database
    
   // starting timer
    th.start();
    th.suspend();
    
    // starting timer 2
    tm.start();
    tm.suspend();
    
    game_engine(); 
    }//GEN-LAST:event_formWindowOpened

    private void op4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op4MouseClicked
        // TODO add your handling code here:
    
      if(ans.equals("4"))  
      {
          op4.setText("    CORRECT");
          op4.setOpaque(true);
          op4.setBackground(Color.green);
          sound();
         tm.resume(); 
         //calling correct 
         
      }
      else
      {
          op4.setText("    WRONG");
          op4.setOpaque(true);
          op4.setBackground(Color.red);
       
          wrong(); 
      }
    
    }//GEN-LAST:event_op4MouseClicked

    private void o5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o5MouseClicked

    private void op3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op3MouseClicked
        // TODO add your handling code here:
          if(ans.equals("3"))  
      {
          op3.setText("    CORRECT");
          op3.setOpaque(true);
          op3.setBackground(Color.green);
          sound();
          tm.resume();
      }
      else
      {
          op3.setText("    WRONG");
          op3.setOpaque(true);
          op3.setBackground(Color.red);
     
          wrong(); 
      }

    }//GEN-LAST:event_op3MouseClicked

    private void o6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o6MouseClicked

    private void op1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op1MouseClicked
        // TODO add your handling code here:
          if(ans.equals("1"))  
      {
          op1.setText("    CORRECT");
          op1.setOpaque(true);
          op1.setBackground(Color.green);
          sound();
          tm.resume(); 
      }
      else
      {
          op1.setText("    WRONG");
          op1.setOpaque(true);
          op1.setBackground(Color.red);
          wrong();
      }

    }//GEN-LAST:event_op1MouseClicked

    private void o11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o11MouseClicked

    private void o12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o12MouseClicked

    private void o13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o13MouseClicked

    private void op2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op2MouseClicked
        // TODO add your handling code here:
          if(ans.equals("2"))  
      {
          System.out.println("JJJJJJJJJ " + ans);
          op2.setText("    CORRECT");
          op2.setOpaque(true);
          op2.setBackground(Color.green);
          sound();
          tm.resume();
      }
      else
      {
          op2.setText("    WRONG");
          op2.setOpaque(true);
          op2.setBackground(Color.red);
          
          wrong();
      }

    }//GEN-LAST:event_op2MouseClicked

    private void o9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o9MouseClicked

    private void o16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o16MouseClicked

    private void o17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o17MouseClicked

    private void o18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o18MouseClicked

    private void PRIZEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRIZEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PRIZEMouseClicked

    private void lostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lostMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lostMouseClicked

    private void win1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_win1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_win1MouseClicked

    private void winMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_winMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PLAY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PLAY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PLAY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PLAY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PLAY().setVisible(true);
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PRIZE;
    private javax.swing.JLabel blast;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lost;
    private javax.swing.JLabel num;
    private javax.swing.JLabel o11;
    private javax.swing.JLabel o12;
    private javax.swing.JLabel o13;
    private javax.swing.JLabel o16;
    private javax.swing.JLabel o17;
    private javax.swing.JLabel o18;
    private javax.swing.JLabel o5;
    private javax.swing.JLabel o6;
    private javax.swing.JLabel o9;
    private javax.swing.JLabel op1;
    private javax.swing.JLabel op2;
    private javax.swing.JLabel op3;
    private javax.swing.JLabel op4;
    private javax.swing.JLabel win;
    private javax.swing.JLabel win1;
    // End of variables declaration//GEN-END:variables
}
